# -*- coding: utf-8 -*-
"""Aula 4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nse8HoojAiswUEyWhwQRLgqg0Ei7RlCs
"""

# Exercício 1: Verificação de Número Positivo

# Escreva um programa em Python que solicite ao usuário um número inteiro e verifique se o número é positivo, negativo ou zero. Em seguida, exiba uma mensagem apropriada de acordo com o resultado da verificação.

numero = int(input('digite um numero inteiro:' ))

if numero > 0:
  print('maior que zero')

elif numero == 0:
  print("zero")

else:
  print('menor que zero')

# Exercício 2: Classificação de Triângulos Escreva um programa em Python que receba três comprimentos de lados de um triângulo e determine se o triângulo é equilátero, isósceles ou escaleno.

iso = 2 lados iguais
equi = 3 lados iguais
esca  = todos lados diferente

tri1 = int(input(digite um valor))
tri2 = int(input(digite um valor))
tri3 = int(input(digite um valor))

if tri1



# Exercício 3: Verificação de Ano Bissexto Um ano é bissexto se for divisível por 4, exceto para anos que são divisíveis por 100. No entanto, anos divisíveis por 400 também são bissextos. Escreva um programa em Python que solicite um ano ao usuário
# e determine se é um ano bissexto ou não.